import image24 from "../../portfolio/alphaWeb27.png";
import image25 from "../../portfolio/alphaWeb29.png";
import image27 from "../../portfolio/alphaWeb33.png";
import image28 from "../../portfolio/alphaWeb35.png";
import image29 from "../../portfolio/alphaWeb37.png";
import image31 from "../../portfolio/alphaWeb41.png";
import image32 from "../../portfolio/alphaWeb43.png";

const products = [
  {
    id: 1,
    image_url: image32,
    name: "Essay on Demand Login",
    type: "Web Application",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "webapp",
  },
  {
    id: 1,
    image_url: image32,
    name: "Make a Cake",
    type: "App Development",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "app",
  },
  {
    id: 1,
    image_url: image32,
    name: "Essay on Demand Rating",
    type: "Web Development",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "webapp",
  },
  {
    id: 1,
    image_url: image32,
    name: "Real Estate",
    type: "App Development",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "app",
  },
  {
    id: 1,
    image_url: image32,
    name: "Essay on Demand Category",
    type: "App Application",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "webapp",
  },
  {
    id: 1,
    image_url: image32,
    name: "Essay on Demand Customer feedback",
    type: "Web Development",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "webapp",
  },
  {
    id: 1,
    image_url: image32,
    name: "Essay on Demand Client Review",
    type: "Web Application",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "webapp",
  },
  {
    id: 1,
    image_url: image32,
    name: "Essay on Demand FAQs",
    type: "Web Development",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "webapp",
  },
  {
    id: 1,
    image_url: image32,
    name: "Let's Love Quran",
    type: "App Development",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "app",
  },
  {
    id: 1,
    image_url: image32,
    name: "Essay on Demand Blogs",
    type: "Web Development",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "webapp",
  },
  {
    id: 1,
    image_url: image32,
    name: "Customer Support App",
    type: "App Development",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "app",
  },
  {
    id: 1,
    image_url: image32,
    name: "Essay on Demand Services",
    type: "Web Development",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "webapp",
  },
  {
    id: 1,
    image_url: image32,
    name: "Essay on Demand Authors",
    type: "Web Development",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "webapp",
  },
  {
    id: 1,
    image_url: image32,
    name: "Essay on Demand Author's Rating",
    type: "Web Application",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "webapp",
  },
  {
    id: 1,
    image_url: image32,
    name: "Mobile Safe",
    type: "App Development",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "app",
  },
  {
    id: 1,
    image_url: image32,
    name: "Make a Cake",
    type: "App Development",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "app",
  },
  {
    id: 1,
    image_url: image32,
    name: "Essay On Demand Contact Us",
    type: "Web Development",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "webapp",
  },
  {
    id: 1,
    image_url: image32,
    name: "GMS Revenue Sheet",
    type: "Web Development",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "webapp",
  },
  {
    id: 1,
    image_url: image32,
    name: "Gym Panel",
    type: "Web Development",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "webapp",
  },
  {
    id: 1,
    image_url: image32,
    name: "Tourism",
    type: "App Development",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "app",
  },
  {
    id: 1,
    image_url: image32,
    name: "GMS Login",
    type: "Web Application",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "webapp",
  },
  {
    id: 1,
    image_url: image32,
    name: "Real Time Location",
    type: "App Development",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "app",
  },
  {
    id: 1,
    image_url: image32,
    name: "Gym Freak",
    type: "Web Development",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "webapp",
  },
  {
    id: 1,
    image_url: image32,
    name: "Cash Cab",
    type: "App Development",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "app",
  },
  {
    id: 1,
    image_url: image32,
    name: "Khan Burger Dashboard",
    type: "Web Development",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "webapp",
  },
  {
    id: 1,
    image_url: image32,
    name: "Ramzan Electronics",
    type: "App Development",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "app",
  },

  {
    id: 1,
    image_url: image32,
    name: "Fahad's Portfolio",
    type: "Web Development",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    sort: "webapp",
  },
];

export default portfolioprojects;
