import affan from "../../portfolio/affan.jpg";
import ayesha from "../../portfolio/ayeshaBukhari.jpg";
import bilal from "../../portfolio/BilalShuja.jpg";
import faraz from "../../portfolio/Faraz.jpg";
import iqra from "../../portfolio/IqraRasheed.jpg";
import sarib from "../../portfolio/Sarib.jpg";
import usama from "../../portfolio/usama.jpg";
import waleed from "../../portfolio/waleed.jpg";
import nauman from "../../portfolio/noman.jpg";

const teammembers = [
  {
    id: 1,
    image: usama,
    name: "Usama Abdullah",
    designation: "Director",
    projectsDone: "100",
    followers: "100",
    following: "100",
    linkedin: "",
    github: "",
    instagram: "",
    description: "I'm Usama Abdullah, a passionate software engineer and the Director of Alphanite Softs. With a strong dedication to the field of technology and a drive for excellence, I have been leading our software development company to deliver exceptional solutions for businesses.My Journey My journey in the world of software engineering began with a deep fascination for coding and problem-solving. Over the years, I have honed my skills and expertise in various programming languages, frameworks, and development methodologies. This journey has equipped me with a solid foundation to create innovative and efficient software solutions. Vision and Mission At Alphanite Softs, our vision is to empower businesses through cutting-edge technology. We strive to provide tailored software solutions that drive growth, enhance productivity, and streamline operations for our clients. Our mission is to exceed expectations by delivering high-quality products that make a meaningful impact. Expertise and Leadership With my experience and expertise in software engineering, I lead a team of talented professionals who share a common passion for technology. Together, we bring forth our diverse skill sets to create custom software solutions, web and mobile applications, and other digital products that meet the unique needs of our clients. Client-Centric Approach I believe in building strong and long-lasting relationships with our clients. Understanding their business objectives, challenges, and goals is at the forefront of our approach. By combining our technical knowledge with a client-centric mindset, we develop solutions that are tailored to their specific requirements and drive tangible results. Continuous Innovation As technology continues to evolve, I am committed to staying up-to-date with the latest advancements in the industry. This enables us to leverage the most cutting-edge tools, frameworks, and methodologies in our software development process. By embracing innovation, we ensure that our clients stay ahead of the curve in their respective industries. Get in Touch Whether you have a software project in mind or you're looking for expert guidance and consultation, I am here to assist you. Feel free to reach out to me directly through the contact information provided on our website. I look forward to the opportunity to collaborate and help you achieve your business objectives through technology.",
    technology: "",
  },
  {
    id: 2,
    image: sarib,
    name: "Sarib Arshad Khan",
    designation: "Chief Executive Officer",
    projectsDone: "100",
    followers: "100",
    following: "100",
    linkedin: "",
    github: "",
    instagram: "",
    description: "",
    technology: "",
  },
  {
    id: 3,
    image: iqra,
    name: "Iqra Rasheed",
    designation: "Regional Operations Manager",
    projectsDone: "100",
    followers: "100",
    following: "100",
    linkedin: "",
    github: "",
    instagram: "",
    description: "",
    technology: "",
  },
  {
    id: 4,
    image: bilal,
    name: "Bilal Shuja",
    designation: "Full Stack Developer / Team Lead",
    projectsDone: "100",
    followers: "100",
    following: "100",
    linkedin: "",
    github: "",
    instagram: "",
    description: "I am a passionate full-stack developer with over 1.5 years of experience in web application development. Since 2021, I have been actively involved in the vast field of IT, where I find immense joy in working with technology, design, and innovation. My expertise lies in fixing and developing robust web applications using modern technologies such as HTML, CSS, JavaScript, React, React Query , Vite including Node.js(Express) and mySQL(database). I thoroughly enjoy exploring new possibilities and pushing the boundaries of what can be achieved in the web application space.",
    technology: "",
  },

  {
    id: 5,
    image: waleed,
    name: "Waleed Ilyas Khan",
    designation: "Network Engineer/Full Stack Developer",
    projectsDone: "100",
    followers: "100",
    following: "100",
    linkedin: "",
    github: "",
    instagram: "",
    description: "",
    technology: "",
  },
  {
    id: 6,
    image: ayesha,
    name: "Ayesha Bukhari",
    designation: "Human Resource",
    projectsDone: "100",
    followers: "100",
    following: "100",
    linkedin: "",
    github: "",
    instagram: "",
    description: "",
    technology: "",
  },
  {
    id: 7,
    image: affan,
    name: "Affan Shiekh",
    designation: "Full Stack Developer",
    projectsDone: "100",
    followers: "100",
    following: "100",
    linkedin: "",
    github: "",
    instagram: "",
    description: "My name is Affan, and I'm a Laravel backend developer with a passion for creating elegant and efficient code. I believe that the key to success in software development is a combination of strong technical skills and excellent communication, and I strive to excel in both areas.",
    technology: "",
  },
  {
    id: 8,
    image: faraz,
    name: "Faraz Mahmood",
    designation: "Full Stack Developer",
    projectsDone: "100",
    followers: "100",
    following: "100",
    linkedin: "",
    github: "",
    instagram: "",
    description: "",
    technology: "",
  },
  {
    id: 9,
    image: nauman,
    name: "Nauman Zafar",
    designation: "UI/ UX Designer",
    projectsDone: "100",
    followers: "100",
    following: "100",
    linkedin: "",
    github: "",
    instagram: "",
    description: "",
    technology: "",
  },
];

export default teammembers;
