import affan from "../../portfolio/affan.jpg";
import ayesha from "../../portfolio/ayeshaBukhari.jpg";
import bilal from "../../portfolio/BilalShuja.jpg";
import faraz from "../../portfolio/Faraz.jpg";
import iqra from "../../portfolio/IqraRasheed.jpg";
import sarib from "../../portfolio/Sarib.jpg";
import usama from "../../portfolio/usama.jpg";
import waleed from "../../portfolio/waleed.jpg";
import nauman from "../../portfolio/noman.jpg";

const teammembers = [
  {
    id: 1,
    image: usama,
    name: "Usama Abdullah",
    designation: "Director",
    projectsDone: "100",
    followers: "100",
    following: "100",
    linkedin: "",
    github: "",
    instagram: "",
    description: "",
    technology: "",
  },
  {
    id: 2,
    image: sarib,
    name: "Sarib Arshad Khan",
    designation: "Chief Executive Officer",
    projectsDone: "100",
    followers: "100",
    following: "100",
    linkedin: "",
    github: "",
    instagram: "",
    description: "",
    technology: "",
  },
  {
    id: 3,
    image: iqra,
    name: "Iqra Rasheed",
    designation: "Regional Operations Manager",
    projectsDone: "100",
    followers: "100",
    following: "100",
    linkedin: "",
    github: "",
    instagram: "",
    description: "",
    technology: "",
  },
  {
    id: 4,
    image: bilal,
    name: "Bilal Shuja",
    designation: "Full Stack Developer / Team Lead",
    projectsDone: "100",
    followers: "100",
    following: "100",
    linkedin: "",
    github: "",
    instagram: "",
    description: "",
    technology: "",
  },

  {
    id: 5,
    image: waleed,
    name: "Waleed Ilyas Khan",
    designation: "Network Engineer/Full Stack Developer",
    projectsDone: "100",
    followers: "100",
    following: "100",
    linkedin: "",
    github: "",
    instagram: "",
    description: "",
    technology: "",
  },
  {
    id: 6,
    image: ayesha,
    name: "Ayesha Bukhari",
    designation: "Human Resource",
    projectsDone: "100",
    followers: "100",
    following: "100",
    linkedin: "",
    github: "",
    instagram: "",
    description: "",
    technology: "",
  },
  {
    id: 7,
    image: affan,
    name: "Affan Shiekh",
    designation: "Full Stack Developer",
    projectsDone: "100",
    followers: "100",
    following: "100",
    linkedin: "",
    github: "",
    instagram: "",
    description: "",
    technology: "",
  },
  {
    id: 8,
    image: faraz,
    name: "Faraz Mahmood",
    designation: "Full Stack Developer",
    projectsDone: "100",
    followers: "100",
    following: "100",
    linkedin: "",
    github: "",
    instagram: "",
    description: "",
    technology: "",
  },
  {
    id: 9,
    image: nauman,
    name: "Nauman Zafar",
    designation: "UI/ UX Designer",
    projectsDone: "100",
    followers: "100",
    following: "100",
    linkedin: "",
    github: "",
    instagram: "",
    description: "",
    technology: "",
  },
];

export default teammembers;
